Rewrite into full Java
OneLiteFeatherNET/OwnGarden pull request #3
Opened 2024-03-22 01:59 UTC by Romindous

A rework of the kotlin / java class mixup

2024-03-23 15:45 UTC, TheMeinerLP requested changes

2024-03-23 15:45 UTC, TheMeinerLP commented on build.gradle.kts
> +    }*/
Remove comment our code

2024-03-23 15:45 UTC, TheMeinerLP commented on src/main/java/fr/skyost/owngarden/OwnGarden.java
> +        Bukkit.getConsoleSender().sendMessage(Component.text("[" + getName() + "]").append(Component.text(message, color)));
Replace with a real logger. ComponentLogger from adventure for example for ansi support

2024-03-23 21:34 UTC, Romindous commented on src/main/java/fr/skyost/owngarden/OwnGarden.java
> +        Bukkit.getConsoleSender().sendMessage(Component.text("[" + getName() + "]").append(Component.text(message, color)));
![image](https://github.com/OneLiteFeatherNET/OwnGarden/assets/64203160/cbdba1cf-56c8-48b6-81d4-32927455ea73)

2024-03-23 21:36 UTC, TheMeinerLP commented on src/main/java/fr/skyost/owngarden/OwnGarden.java
> +        Bukkit.getConsoleSender().sendMessage(Component.text("[" + getName() + "]").append(Component.text(message, color)));
Replace overall all log methid usages.

2024-03-23 21:41 UTC, TheMeinerLP commented on src/main/java/fr/skyost/owngarden/OwnGarden.java
> +//        Bukkit.getConsoleSender().sendMessage(Component.text("[" + getName() + "]").append(Component.text(message, color)));
Try to remove this method.

2024-04-05 22:12 UTC, TheMeinerLP requested changes

2024-04-05 22:12 UTC, TheMeinerLP commented on src/main/java/fr/skyost/owngarden/OwnGarden.java
> +    public final ComponentLogger logger = ComponentLogger.logger(getName());
Work with getter

2024-04-05 22:12 UTC, TheMeinerLP commented on src/main/java/fr/skyost/owngarden/OwnGarden.java
> +            .build()).build();
You dont need this, because `MiniMessage.miniMessage().deserialize("your string")` does the same

2024-04-05 22:12 UTC, TheMeinerLP commented on src/main/java/fr/skyost/owngarden/OwnGarden.java
> +    public static final String TREES = "trees";
Extract into extra class for constants

2024-04-05 22:12 UTC, TheMeinerLP commented on src/main/java/fr/skyost/owngarden/OwnGarden.java
> +        } else operations = new DefaultUtils();
Add braces for better readability

2024-04-05 22:12 UTC, TheMeinerLP commented on src/main/java/fr/skyost/owngarden/OwnGarden.java
> +    }
Put that into extra class

2024-04-05 22:12 UTC, TheMeinerLP commented on src/main/java/fr/skyost/owngarden/OwnGarden.java
> +//        logger.info(Component.text(treeMap.toString()));
Remove debug code

2024-04-05 22:12 UTC, TheMeinerLP commented on src/main/java/fr/skyost/owngarden/command/OwnGardenCommand.java
> +        if (!sender.hasPermission("owngarden.command")) {
Permission check can be done via plugin.yml

2024-04-05 22:12 UTC, TheMeinerLP commented on src/main/java/fr/skyost/owngarden/command/OwnGardenCommand.java
> +        plugin.loadConfigs();
Config is only once loaded

2024-04-05 22:12 UTC, TheMeinerLP commented on src/main/java/fr/skyost/owngarden/command/OwnGardenCommand.java
> +        plugin.loadSchematics();
Also this is only once loaded needed

2024-04-05 22:12 UTC, TheMeinerLP commented on src/main/java/fr/skyost/owngarden/command/OwnGardenCommand.java
> +        }
Extra that into an extra command. Because readability.

2024-04-05 22:12 UTC, TheMeinerLP commented on src/main/java/fr/skyost/owngarden/data/MaterialSchems.java
> +    }*/
Remove debug code

2024-04-05 22:12 UTC, TheMeinerLP commented on src/main/java/fr/skyost/owngarden/worldedit/DefaultUtils.java
> +public class DefaultUtils implements Utils{
Space and missing `final` modifier

2024-04-05 22:12 UTC, TheMeinerLP commented on src/main/java/fr/skyost/owngarden/worldedit/Utils.java
> +//    String[] FAWE_VERSIONS = {"2.9.1", "2.9.2"};
remove old / debug code

2024-04-05 22:12 UTC, TheMeinerLP commented on src/main/java/fr/skyost/owngarden/worldedit/Utils.java
> +        return false;*/ // FAWE methods are (probably) stable with versions
Also, here remove old code

2024-04-05 22:12 UTC, TheMeinerLP commented on src/main/java/fr/skyost/owngarden/worldedit/Utils.java
> +        final Plugin we = Bukkit.getPluginManager().getPlugin("FastAsyncWorldEdit");
Just check if "WorldEdit" here. Because FAWE provide `WorldEdit` via Provider field over the plugin.yml

2024-04-05 22:12 UTC, TheMeinerLP commented on src/main/java/fr/skyost/owngarden/worldedit/WorldEditUtils.java
> +        return pass;
Flat the structure for readability

2024-04-05 22:12 UTC, TheMeinerLP commented on src/main/java/fr/skyost/owngarden/worldedit/WorldEditUtils.java
> +        if (format == null) throw new IOException("Unknown schematic format : " + path.toString());
Add brace

2024-04-05 22:12 UTC, TheMeinerLP commented on src/main/java/fr/skyost/owngarden/worldedit/WorldEditUtils.java
> +        if (!Files.exists(path)) {
The `!` Can be overseen. Extra into variable.
For example:
```java
if (!Files.exists(path)) {
...
}
```
```java
var pathIsNotExist = !Files.exists(path);
if (pathIsNotExist) {
...
}
```

What is better to read as a newbie ?

2024-04-05 22:12 UTC, TheMeinerLP commented on src/main/java/fr/skyost/owngarden/worldedit/WorldEditUtils.java
> +        }
Remove ex.printStackTrace and handle the exception fully. 
To handle right, ask your self with: Can the run the plugin still if it fails here ?

2024-04-05 22:12 UTC, TheMeinerLP commented on src/main/java/fr/skyost/owngarden/worldedit/WorldEditUtils.java
> +            session.close();
Get bin closes with try-and-catch-with-resources

2024-04-05 22:12 UTC, TheMeinerLP commented on src/main/java/fr/skyost/owngarden/worldedit/WorldEditUtils.java
> +        BinaryTagIO.writer().write(root, new FileOutputStream(file), BinaryTagIO.Compression.GZIP);*/
Remove boiler code

2024-04-05 22:12 UTC, TheMeinerLP commented on build.gradle.kts
> +val grp = group
Is this needed ?

2024-04-05 22:12 UTC, TheMeinerLP commented on build.gradle.kts
>          }
This is not needed instead of `mergeServiceFiles`

2024-04-05 23:50 UTC, merged